version: "3.3"
services:
  database:
    hostname: postgres-db
    image: postgres:13
    container_name: siuwi-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "13000:8080"
